services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ../../settings/.env
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: